<?php
namespace app\api\controller;

use \app\common\library\Code;
use think\exception\HttpException;

class Test extends Base
{
    protected $reportUrl;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub


    }

    public function test()
    {
    	$params = $this->param;
    // var_dump($params);die;
    	if (true !== ($validate = $this->validate($params, 'PublicParams'))) {
            var_dump($validate,'55');die;
        }
        var_dump($validate,'22');die;

    	$a = $_SERVER['HTTP_USER_AGENT'];
    	var_dump($a);die;
        $params = $this->param;
        var_dump(Code::PARAM_ERROR);die;
        return apiResult('0', 132, 465);
        echo 22;die;
    }

    public function abc()
    {
        $params = $this->param;
        echo 44;die;
    }



   

}